import React, { useState } from 'react';
import { DollarSign, Clock, MapPin, Plane, TrendingUp, Sparkles, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';
import { predictPrice, getModelInfo, FLIGHT_OPTIONS } from '../api/client';
import './PricePrediction.css';

const PricePrediction = () => {
    const [formData, setFormData] = useState({
        airline: 'Vistara',
        source_city: 'Delhi',
        destination_city: 'Mumbai',
        departure_time: 'Morning',
        arrival_time: 'Afternoon',
        stops: 'one',
        class: 'Economy',
        duration: 2.5,
        days_left: 10,
    });

    const [prediction, setPrediction] = useState(null);
    const [modelInfo, setModelInfo] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData((prev) => ({
            ...prev,
            [name]: name === 'duration' || name === 'days_left' ? Number(value) : value,
        }));
    };

    const handlePredict = async (e) => {
        e.preventDefault();

        if (formData.source_city === formData.destination_city) {
            toast.error('Source and destination cities must be different');
            return;
        }

        setLoading(true);
        setError(null);

        try {
            const [predictionResult, info] = await Promise.all([
                predictPrice(formData),
                getModelInfo(),
            ]);
            setPrediction(predictionResult);
            setModelInfo(info);
            toast.success('Price prediction generated by the live model');
        } catch (err) {
            const message =
                err.response?.data?.detail?.[0]?.msg ||
                err.response?.data?.detail ||
                'Could not reach the prediction API. Is the backend running on :8000?';
            setError(typeof message === 'string' ? message : 'Prediction request failed');
            toast.error('Prediction failed');
        } finally {
            setLoading(false);
        }
    };

    const topFeatures = modelInfo
        ? Object.entries(modelInfo.feature_importance).slice(0, 5)
        : [];

    return (
        <div className="price-prediction">
            <div className="page-header">
                <div>
                    <h1 className="page-title">Price Prediction</h1>
                    <p className="page-subtitle">
                        Real XGBoost model trained on 300K+ Indian domestic flight fares
                    </p>
                </div>
            </div>

            <div className="prediction-grid grid grid-cols-2">
                <div className="card prediction-form-card">
                    <div className="card-header">
                        <h3 className="card-title">Flight Details</h3>
                        <span className="badge badge-primary">
                            <Sparkles size={12} />
                            ML Powered
                        </span>
                    </div>

                    <form onSubmit={handlePredict} className="prediction-form">
                        <div className="form-row">
                            <div className="form-group">
                                <label className="form-label">
                                    <MapPin size={16} />
                                    Source City
                                </label>
                                <select
                                    name="source_city"
                                    value={formData.source_city}
                                    onChange={handleInputChange}
                                    className="select"
                                >
                                    {FLIGHT_OPTIONS.cities.map((c) => (
                                        <option key={c.value} value={c.value}>{c.label}</option>
                                    ))}
                                </select>
                            </div>

                            <div className="form-group">
                                <label className="form-label">
                                    <MapPin size={16} />
                                    Destination City
                                </label>
                                <select
                                    name="destination_city"
                                    value={formData.destination_city}
                                    onChange={handleInputChange}
                                    className="select"
                                >
                                    {FLIGHT_OPTIONS.cities.map((c) => (
                                        <option key={c.value} value={c.value}>{c.label}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div className="form-row">
                            <div className="form-group">
                                <label className="form-label">
                                    <Clock size={16} />
                                    Departure Time
                                </label>
                                <select
                                    name="departure_time"
                                    value={formData.departure_time}
                                    onChange={handleInputChange}
                                    className="select"
                                >
                                    {FLIGHT_OPTIONS.timesOfDay.map((t) => (
                                        <option key={t.value} value={t.value}>{t.label}</option>
                                    ))}
                                </select>
                            </div>

                            <div className="form-group">
                                <label className="form-label">
                                    <Clock size={16} />
                                    Arrival Time
                                </label>
                                <select
                                    name="arrival_time"
                                    value={formData.arrival_time}
                                    onChange={handleInputChange}
                                    className="select"
                                >
                                    {FLIGHT_OPTIONS.timesOfDay.map((t) => (
                                        <option key={t.value} value={t.value}>{t.label}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div className="form-row">
                            <div className="form-group">
                                <label className="form-label">
                                    <Plane size={16} />
                                    Stops
                                </label>
                                <select
                                    name="stops"
                                    value={formData.stops}
                                    onChange={handleInputChange}
                                    className="select"
                                >
                                    {FLIGHT_OPTIONS.stops.map((s) => (
                                        <option key={s.value} value={s.value}>{s.label}</option>
                                    ))}
                                </select>
                            </div>

                            <div className="form-group">
                                <label className="form-label">
                                    <Sparkles size={16} />
                                    Class
                                </label>
                                <select
                                    name="class"
                                    value={formData.class}
                                    onChange={handleInputChange}
                                    className="select"
                                >
                                    {FLIGHT_OPTIONS.classes.map((c) => (
                                        <option key={c.value} value={c.value}>{c.label}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div className="form-row">
                            <div className="form-group">
                                <label className="form-label">
                                    <Clock size={16} />
                                    Duration (hours)
                                </label>
                                <input
                                    type="number"
                                    name="duration"
                                    min="0.5"
                                    max="49.9"
                                    step="0.1"
                                    value={formData.duration}
                                    onChange={handleInputChange}
                                    className="input"
                                    required
                                />
                            </div>

                            <div className="form-group">
                                <label className="form-label">
                                    <Clock size={16} />
                                    Days Until Departure
                                </label>
                                <input
                                    type="number"
                                    name="days_left"
                                    min="1"
                                    max="49"
                                    value={formData.days_left}
                                    onChange={handleInputChange}
                                    className="input"
                                    required
                                />
                            </div>
                        </div>

                        <div className="form-group">
                            <label className="form-label">
                                <Plane size={16} />
                                Airline
                            </label>
                            <select
                                name="airline"
                                value={formData.airline}
                                onChange={handleInputChange}
                                className="select"
                            >
                                {FLIGHT_OPTIONS.airlines.map((a) => (
                                    <option key={a.value} value={a.value}>{a.label}</option>
                                ))}
                            </select>
                        </div>

                        <button type="submit" className="btn btn-primary btn-large" disabled={loading}>
                            {loading ? (
                                <>
                                    <div className="animate-spin">⏳</div>
                                    Predicting...
                                </>
                            ) : (
                                <>
                                    <TrendingUp size={20} />
                                    Predict Price
                                </>
                            )}
                        </button>

                        {error && (
                            <p className="form-error" style={{ color: '#ef4444', marginTop: '8px' }}>
                                {error}
                            </p>
                        )}
                    </form>
                </div>

                <div className="prediction-results">
                    {prediction ? (
                        <>
                            <div className="card price-result-card">
                                <div className="price-result-header">
                                    <DollarSign size={32} className="price-icon" />
                                    <div>
                                        <p className="price-label">Predicted Price</p>
                                        <h2 className="price-value">
                                            ₹{prediction.predicted_price.toLocaleString('en-IN')}
                                        </h2>
                                        <p className="price-confidence">
                                            Model {prediction.model_version}
                                            {prediction.out_of_distribution && (
                                                <span className="badge badge-warning" style={{ marginLeft: '8px' }}>
                                                    <AlertTriangle size={12} /> Low confidence — unusual inputs
                                                </span>
                                            )}
                                        </p>
                                    </div>
                                </div>

                                <div className="price-range">
                                    <div className="price-range-item">
                                        <span className="price-range-label">Low</span>
                                        <span className="price-range-value">
                                            ₹{prediction.confidence_low.toLocaleString('en-IN')}
                                        </span>
                                    </div>
                                    <div className="price-range-bar">
                                        <div className="price-range-indicator"></div>
                                    </div>
                                    <div className="price-range-item">
                                        <span className="price-range-label">High</span>
                                        <span className="price-range-value">
                                            ₹{prediction.confidence_high.toLocaleString('en-IN')}
                                        </span>
                                    </div>
                                </div>
                            </div>

                            {modelInfo && (
                                <div className="card">
                                    <div className="card-header">
                                        <h3 className="card-title">Top Price Drivers (real feature importance)</h3>
                                    </div>
                                    <div className="factors-list">
                                        {topFeatures.map(([name, score]) => (
                                            <div key={name} className="factor-item">
                                                <div className="factor-info">
                                                    <span className="factor-name">{name}</span>
                                                </div>
                                                <span className="factor-value">{(score * 100).toFixed(1)}%</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {modelInfo && (
                                <div className="card">
                                    <div className="card-header">
                                        <h3 className="card-title">Model Accuracy (held-out test set)</h3>
                                    </div>
                                    <ul className="recommendations-list">
                                        <li className="recommendation-item">
                                            <Sparkles size={16} className="recommendation-icon" />
                                            MAE: ₹{modelInfo.metrics.mae.toFixed(0)} | R²: {modelInfo.metrics.r2.toFixed(3)}
                                        </li>
                                        <li className="recommendation-item">
                                            <Sparkles size={16} className="recommendation-icon" />
                                            Trained on {modelInfo.dataset}
                                        </li>
                                    </ul>
                                </div>
                            )}
                        </>
                    ) : (
                        <div className="card empty-state">
                            <div className="empty-state-content">
                                <DollarSign size={64} className="empty-state-icon" />
                                <h3 className="empty-state-title">No Prediction Yet</h3>
                                <p className="empty-state-text">
                                    Fill in the flight details and click "Predict Price" to query the live model
                                </p>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default PricePrediction;
