"""add predict fields to saved_searches

Revision ID: 4e2322424d89
Revises: de88570c222a
Create Date: 2026-07-20 21:03:10.981817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2322424d89'
down_revision: Union[str, Sequence[str], None] = 'de88570c222a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_searches', sa.Column('airline', sa.String(length=20), nullable=False))
    op.add_column('saved_searches', sa.Column('departure_time', sa.String(length=20), nullable=False))
    op.add_column('saved_searches', sa.Column('arrival_time', sa.String(length=20), nullable=False))
    op.add_column('saved_searches', sa.Column('stops', sa.String(length=20), nullable=False))
    op.add_column('saved_searches', sa.Column('departure_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_searches', 'departure_date')
    op.drop_column('saved_searches', 'stops')
    op.drop_column('saved_searches', 'arrival_time')
    op.drop_column('saved_searches', 'departure_time')
    op.drop_column('saved_searches', 'airline')
    # ### end Alembic commands ###
